name: check disk space

on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: list block devices
        shell: bash
        run: |
          lsblk
      - name: show free space
        shell: bash
        run: |
          df -h
